# Generated by Django 5.2.5 on 2025-09-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epi',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='epi',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='epi',
            name='quantidade_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='epi',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
