# Generated by Django 5.2.5 on 2025-09-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0002_epi_descricao_epi_quantidade_disponivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epi',
            name='quantidade_disponivel',
        ),
    ]
