# Generated by Django 5.2.5 on 2025-09-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0003_remove_epi_quantidade_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='epi',
            name='quantidade_danificada',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
