# Generated by Django 5.2.5 on 2025-09-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
